-- ==============================================================================
-- STUDIO DASHBOARD — SUPABASE SCHEMA & POLICIES
-- Run this script in the Supabase Dashboard -> SQL Editor (or via CLI)
-- ==============================================================================

-- 1. CLIENTS TABLE
CREATE TABLE IF NOT EXISTS public.clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  company TEXT DEFAULT '',
  email TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  address TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. PROJECTS TABLE
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  client_id BIGINT,
  client_name TEXT NOT NULL,
  client_company TEXT DEFAULT '',
  value NUMERIC NOT NULL DEFAULT 0,
  start_date TEXT DEFAULT '',
  deadline TEXT DEFAULT '',
  status TEXT DEFAULT 'In Progress',
  notes TEXT DEFAULT '',
  plan JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. QUOTATIONS TABLE
CREATE TABLE IF NOT EXISTS public.quotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number TEXT NOT NULL,
  title TEXT NOT NULL,
  client_id BIGINT,
  client_name TEXT NOT NULL,
  client_company TEXT DEFAULT '',
  items JSONB DEFAULT '[]'::jsonb,
  total NUMERIC NOT NULL DEFAULT 0,
  status TEXT DEFAULT 'Draft',
  valid_until TEXT DEFAULT '',
  date TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

-- CREATE PERMISSIVE POLICIES FOR ANON / PUBLISHABLE KEY ACCESS
CREATE POLICY "Allow public read clients" ON public.clients FOR SELECT USING (true);
CREATE POLICY "Allow public insert clients" ON public.clients FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update clients" ON public.clients FOR UPDATE USING (true);
CREATE POLICY "Allow public delete clients" ON public.clients FOR DELETE USING (true);

CREATE POLICY "Allow public read projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Allow public insert projects" ON public.projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update projects" ON public.projects FOR UPDATE USING (true);
CREATE POLICY "Allow public delete projects" ON public.projects FOR DELETE USING (true);

CREATE POLICY "Allow public read quotes" ON public.quotes FOR SELECT USING (true);
CREATE POLICY "Allow public insert quotes" ON public.quotes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update quotes" ON public.quotes FOR UPDATE USING (true);
CREATE POLICY "Allow public delete quotes" ON public.quotes FOR DELETE USING (true);

-- ==============================================================================
-- INITIAL SEED DATA (1-2 REALISTIC SAMPLE PROJECTS)
-- ==============================================================================

-- Clear old table rows
TRUNCATE TABLE public.quotes, public.projects, public.clients RESTART IDENTITY CASCADE;

-- Insert 2 Sample Clients
INSERT INTO public.clients (name, company, email, phone, address) VALUES
('Maya Lestari', 'PT Digital Nusantara', 'maya@digitalnusantara.id', '0812-3456-7890', 'Jl. Sudirman No. 45, Jakarta Selatan'),
('Rizky Hartono', 'PT Mahakarya Prima', 'rizky@mahakarya.co.id', '0813-9876-5432', 'Jl. Gatot Subroto Kav. 12, Jakarta Selatan');

-- Insert 2 Sample Projects
INSERT INTO public.projects (name, client_id, client_name, client_company, value, start_date, deadline, status, notes, plan) VALUES
(
  'Brand Identity & UI Design System',
  1,
  'Maya Lestari',
  'PT Digital Nusantara',
  15000000,
  '2026-10-01',
  '2026-11-15',
  'In Progress',
  'Proyek perancangan visual identity baru dan UI kit web app.',
  '[
    { "id": 1, "t": "Down payment 50%", "pct": 50, "a": 7500000, "due": "2026-10-05", "pd": "2026-10-05", "paid": true, "note": "BCA Transfer - Lunas" },
    { "id": 2, "t": "Final payment 50%", "pct": 50, "a": 7500000, "due": "2026-11-15", "pd": null, "paid": false, "note": "Menunggu serah terima aset final" }
  ]'::jsonb
),
(
  'Company Profile Website Development',
  2,
  'Rizky Hartono',
  'PT Mahakarya Prima',
  12000000,
  '2026-09-15',
  '2026-10-25',
  'In Progress',
  'Development website company profile responsif dengan CMS.',
  '[
    { "id": 1, "t": "Termin 1 (DP 40%)", "pct": 40, "a": 4800000, "due": "2026-09-20", "pd": "2026-09-20", "paid": true, "note": "Mandiri Transfer - Lunas" },
    { "id": 2, "t": "Termin 2 (Pelunasan 60%)", "pct": 60, "a": 7200000, "due": "2026-10-25", "pd": null, "paid": false, "note": "Saat deployment production" }
  ]'::jsonb
);

-- Insert 1 Sample Quotation
INSERT INTO public.quotes (number, title, client_id, client_name, client_company, items, total, status, valid_until, date) VALUES
(
  'QUO-2026-001',
  'SEO Optimization & Content Strategy',
  1,
  'Maya Lestari',
  'PT Digital Nusantara',
  '[
    { "d": "Technical SEO Audit & Speed Optimization", "q": 1, "u": 3500000, "t": 3500000 },
    { "d": "Monthly Content Strategy & Keyword Mapping", "q": 1, "u": 2500000, "t": 2500000 }
  ]'::jsonb,
  6000000,
  'Sent',
  '2026-10-20',
  '2026-10-05'
);
